server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://finday-db.chccokm84j4g.ap-northeast-2.rds.amazonaws.com:3306/kookmin_bank?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: "*psy0605751*"
  jpa:
    hibernate:
      ddl-auto: none  # or validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
